# Generated by Django 4.2.27 on 2026-02-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_portal', '0002_initial_categories_subtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product being reviewed (optional for cart-wide review)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mushroom_portal.product'),
        ),
    ]
